# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-20 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0003_create_mymodel_instance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='x',
        ),
        migrations.DeleteModel(
            name='ModelX',
        ),
    ]
